"""Added units table

Revision ID: 0ef8c3da7aa6
Revises: 283ff5470a50
Create Date: 2022-01-17 10:23:56.469874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef8c3da7aa6'
down_revision = '283ff5470a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
