"""Cascade delete

Revision ID: e8a629f5efc3
Revises: b0708aea5823
Create Date: 2022-01-17 15:00:47.470431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a629f5efc3'
down_revision = 'b0708aea5823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('building_parameters_building_id_fkey', 'building_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'building_parameters', 'buildings', ['building_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('buildings_game_id_fkey', 'buildings', type_='foreignkey')
    op.create_foreign_key(None, 'buildings', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('games_user_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unit_parameters_unit_id_fkey', 'unit_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'unit_parameters', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('units_game_id_fkey', 'units', type_='foreignkey')
    op.create_foreign_key(None, 'units', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.create_foreign_key('units_game_id_fkey', 'units', 'games', ['game_id'], ['id'])
    op.drop_constraint(None, 'unit_parameters', type_='foreignkey')
    op.create_foreign_key('unit_parameters_unit_id_fkey', 'unit_parameters', 'units', ['unit_id'], ['id'])
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_user_id_fkey', 'games', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.create_foreign_key('buildings_game_id_fkey', 'buildings', 'games', ['game_id'], ['id'])
    op.drop_constraint(None, 'building_parameters', type_='foreignkey')
    op.create_foreign_key('building_parameters_building_id_fkey', 'building_parameters', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###
